name: Deploy to cPanel

on:
  push:
    branches:
      - main  # Adjust to your main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "$CPanel_SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -t rsa artfinderx.com >> ~/.ssh/known_hosts
        env:
          CPanel_SSH_PRIVATE_KEY: ${{ secrets.CPanel_SSH_PRIVATE_KEY }}

      - name: Deploy to cPanel
        run: |
          scp -r ./build/* artfinde@arfinderx.com:/home/yourcpanelusername/public_html/
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        shell: bash

      - name: Trigger cPanel Refresh
        run: |
          curl -X GET "https://artfinderx.com/cpanel/apps/dostuff.php"  # Adjust the URL to your needs
